os: osx
language: java
java:
  - openjdk11
script:
  - cp settings.xml ~/.m2/settings.xml
  - cd image-train-filters-service
  - sbt "project image-train-filters-service" clean update test
  - cd ..
  - cd image-train-filters-fe
  - npm install
  - cd ..