os: osx
language: java
java:
  - openjdk11
script:
  - echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  - sudo apt-get update
  - sudo apt-get install sbt
  - cp settings.xml ~/.m2/settings.xml
  - cd image-train-filters-service
  - sbt "project image-train-filters-service" clean update test
  - cd ..
  - cd image-train-filters-fe
  - npm install
  - cd ..