os: osx
language: scala
scala:
  - 2.12.2
script:
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk update
  - sdk use java 11.0.4-zulu
  - cd image-train-filters-service
  - sbt "project image-train-filters-service" clean update test
  - cd ..
  - cd image-train-filters-fe
  - brew update
  - brew upgrade npm
  - npm cache clean -f
  - npm install -g n
  - sudo n stable
  - npm install
  - cd ..