os: osx
language: scala
scala:
  - 2.12.2
script:
  - cd image-train-filters-service
  - sbt "project image-train-filters-service" clean update test
  - cd ..
  - cd image-train-filters-fe
  - npm install
  - cd ..