os: linux
language: scala
scala:
  - 2.12.2
script:
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk update
  - sdk install java 12.0.2-zulu
  - sdk use java 12.0.2-zulu
  - cd image-train-filters-service
#  - sbt "project image-train-filters-service" clean update test
  - cd ..
  - cd image-train-filters-fe
  - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
  - sudo apt install nodejs
  - npm install -g n
  - sudo n stable
  - npm install
  - cd ..