os: linux
language: scala

jobs:
  include:
    - language: scala
      stage: Backend Test (All Scala 2.12.2 Services)
      jdk: openjdk11
      scala:
        - 2.13
      script:
        - curl -s "https://get.sdkman.io" | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - sdk update
        - sdk install java 12.0.2-zulu
        - sdk use java 12.0.2-zulu
        - cd image-train-filters-service
        - export COVERALLS_REPO_TOKEN=${COVERALLS_TOKEN}
        - sbt "project image-train-filters-service" clean update coverage test
        - sbt coverageReport coveralls

    - language: node_js
      stage: Frontend Test (Angular Nebular Release)
      node_js: 12
      script:
        - cd image-train-filters-fe
        - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
        - sudo apt install nodejs
        - npm install -g n
        - npm install
        - jest --coverage && coveralls < coverage/lcov.info
        - codecov
