os: linux
language: scala

jobs:
  include:
    - language: node_js
      stage: Frontend Test (Angular Nebular Release)
      node_js: 12
      script:
        - yarn config set workspaces-experimental true
        - yarn install
        - jest --coverage && coveralls < coverage/lcov.info
        - codecov

    - language: scala
      stage: Backend Test (All Scala 2.13.1 Services)
      jdk: openjdk11
      install: export TRAVIS_WORKER_DOCKER_MEMORY=16G
      scala:
        - 2.13
      script:
        - export COVERALLS_REPO_TOKEN=${COVERALLS_TOKEN}
        - sbt "project service" clean update coverage test
        - sbt "project service" jacoco coverageAggregate coverageReport coveralls
        - bash <(curl -s https://codecov.io/bash)
