os: linux
language: scala

jobs:
  include:
    - language: scala
      stage: Backend Test (All Scala 2.12.2 Services)
      jdk: openjdk11
      install: export TRAVIS_WORKER_DOCKER_MEMORY=16G
      scala:
        - 2.13
      script:
        - export COVERALLS_REPO_TOKEN=${COVERALLS_TOKEN}
        - sbt "project service" clean update coverage test
        - sbt "project service" jacoco coverageAggregate coverageReport coveralls
        - bash <(curl -s https://codecov.io/bash)

    - language: node_js
      stage: Frontend Test (Angular Nebular Release)
      node_js: 12
      script:
        - cd image-train-filters-fe
        - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
        - sudo apt install nodejs
        - npm install -g n
        - npm install
        - jest --coverage && coveralls < coverage/lcov.info
        - codecov
