os: osx
language: scala
scala:
  - 2.12.2
script:
  - brew tap caskroom/versions
  - brew cask info java11
  - brew cask info java
  - brew cask install java11
  - brew cask install java
  - cd image-train-filters-service
  - sbt "project image-train-filters-service" clean update test
  - cd ..
  - cd image-train-filters-fe
  - brew update
  - brew upgrade npm
  - brew upgrade node
  - npm cache clean -f
  - npm install -g n
  - n stable
  - cd ..