version: 2
jobs:
  build-service:
    docker:
      - image: jesperancinha/je-all-build-jdk-12:0.0.2

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - run: cd image-train-filters-service && sbt clean update test assembly package

  build-front-end:
    docker:
        - image: cimg/node:12.22.1
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: cd image-train-filters-fe && yarn install

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-service
      - build-front-end